apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: "2024-08-18T03:41:07Z"
  generation: 1
  labels:
    app: random-deploy
  name: random-deploy
  namespace: default
  resourceVersion: "334185"
  uid: 47dc4395-a068-45d2-adef-cc5643df14da
spec:
  progressDeadlineSeconds: 600
  replicas: 10
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: random-deploy
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: random-deploy
    spec:
      containers:
      - image: docker-registry:5000/nginx
        imagePullPolicy: Always
        name: nginx
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
