apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: docker-registry:5000/nginx
        ports:
        - containerPort: 80
        resources:
          # these pods will be just a fraction of one of our cores
          limits:
            cpu: 100m
          requests:
            cpu: 50m
