apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: testdeploy
  name: testdeploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: testdeploy
  template:
    metadata:
      labels:
        app: testdeploy
    spec:
      containers:
      - image: rockylinux:9
        name: rockylinux
        command: ["sleep", "infinity"]
        volumeMounts:
          - mountPath: /tmp/data
            name: test-vol
      volumes:
      - name: test-vol
        persistentVolumeClaim:
          claimName: safari-pvc
