apiVersion: v1
kind: PersistentVolume
metadata:
  name: safari-pv 
spec:
  capacity:
    storage: 20Mi
  volumeMode: Filesystem
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - minikube
  accessModes:
  - ReadWriteOnce
  local:
    path: /tmp/data
