apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: safari-pvc 
spec:
  volumeMode: filesystem
  volumeName: safari-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Mi
