apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mike-stateful-set 
spec:
  selector:
    matchLabels:
      app: mike-stateful-set 
  serviceName: "nginx"
  replicas: 3 
  minReadySeconds: 2 
  template:
    metadata:
      labels:
        app: mike-stateful-set # has to match .spec.selector.matchLabels
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: nginx-stateful-pod
        image: docker-registry:5000/nginx 
