apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: my-oneshot-app 
  name: mike-nginx
spec:
  replicas: 2 
  selector:
    matchLabels:
      app: my-oneshot-app
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: my-oneshot-app
    spec:
      containers:
      - image: docker-registry:5000/nginx
        name: nginx
