apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: my-oneshot-app
  name: my-oneshot-app
spec:
  ports:
  - name: 80-80
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: my-oneshot-app
  type: ClusterIP
status:
  loadBalancer: {}
