apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: testpod
  name: testpod
spec:
  containers:
  - image: docker-registry:5000/alpine
    name: testpod
    resources: {}
    command: ["sleep", "infinity"]
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
