apiVersion: v1
kind: Pod
metadata:
  labels:
    run: testpod1
  name: testpod1
spec:
  containers:
  - image: rockylinux:9
    name: testpod1
    command: ["sleep", "infinity"]
    livenessProbe:
      exec:
        command:
        - echo 
        - alive 
      initialDelaySeconds: 5
      periodSeconds: 5
    readinessProbe:
      exec:
        command:
        - curl
        - http://service-am-i-ready
      initialDelaySeconds: 5
      periodSeconds: 5
  dnsPolicy: ClusterFirst
  restartPolicy: Always
