apiVersion: v1
kind: PersistentVolume
metadata:
  name: vm-image-pv
spec:
  storageClassName: manual
  capacity:
    storage: 17Gi  # Adjust the size to match or exceed your qcow2 image size
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/minikube-share/lubuntu-server.img"
    type: File
