apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: testdeploy
    version: green
  name: testdeploy-green
spec:
  replicas: 2
  selector:
    matchLabels:
      app: testdeploy
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: testdeploy
        version: green
    spec:
      containers:
      - image: docker-registry:5000/test-app:1.02
        name: test-app
        resources: {}
status: {}
