apiVersion: v1
kind: Service
metadata:
  labels:
    app: testdeploy
  name: testdeploy
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: testdeploy
      #version: green 
    version: blue
