apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: secretpod
  name: secretpod
  namespace: secret
spec:
  containers:
  - image: docker-registry:5000/busybox
    name: secretpod
    resources: {}
    envFrom:
    - secretRef:
        name: mikessecret
    command: ["sleep", "infinity"]
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
