apiVersion: v1
kind: Pod
metadata:
  name: hard-to-meet-limits-pod

spec:
  containers:
    - name: hard-to-meet-limits-pod
      image: docker-registry:5000/nginx
      resources:
        requests:
          # at least
          cpu: 4  # 4 cores 
          memory: "5Gi" # ~5gb
