apiVersion: v1
kind: Service
metadata:
  name: nginx-service

spec:
  # type: ClusterIP # internal connections only!
  type: NodePort # for exposed connections!!!
  ports:
    - targetPort: 80
      port: 80
      nodePort: 30000 # where we will access it externally
      protocol: TCP
  selector:
    type: front-end
