apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: secret-deployment
  name: secret-deployment
spec:
  type: NodePort
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
    nodePort: 30080
  selector:
    app: secret-deployment
status:
  loadBalancer: {}
