apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: test-storageclass-pod
  name: test-storageclass-pod
spec:
  containers:
  - image: docker-registry:5000/fedora:39
    name: test-storageclass-pod
    volumeMounts:
      - mountPath: "/data"
        name: my-vol
    command: ["sleep", "infinity"]
  volumes:
    - name: my-vol
      persistentVolumeClaim:
        claimName: local-pvc 
