apiVersion: v1
kind: Service
metadata:
  name: petfinder
spec:
  type: NodePort  # For accessing externally, use NodePort or LoadBalancer in cloud setups
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: server-port
  selector:
    app: petfinder
