apiVersion: apps/v1
kind: Deployment
metadata:
  name: petfinder
spec:
  replicas: 2
  selector:
    matchLabels:
      app: petfinder
  template:
    metadata:
      labels:
        app: petfinder
    spec:
      containers:
      - name: petfinder
        image: registry:5000/petsdblookup:v1
        ports:
        - containerPort: 8080