apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: test-service-account
  name: test-service-account
spec:
  containers:
  - image: docker.io/library/ubuntu 
    imagePullPolicy: Never # only on k3d :) 
    name: test-service-account
    command: ["sleep", "infinity"]
    resources: {}
  serviceAccountName: mikes-service-account
