apiVersion: v1
kind: Service
metadata:
  name: ready-service

spec:
  type: NodePort
  selector:
    app: ready-app
  ports:
  - name: mainport
    port: 5000
    nodePort: 30080
    targetPort: 5000
    protocol: TCP
