apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: pod1
  name: pod1
spec:
  containers:
  - image: httpd
    name: pod1-container 
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  nodeName: minikube  # manual scheduler, skips kube-scheduler
status: {}
