apiVersion: v1
kind: Pod


metadata:
  name: mypod
  labels:
    testlabel: something
spec:
  containers:
    - name: mypod1
      image: docker-registry:5000/nginx
      ports:
        - containerPort: 80
