apiVersion: v1
kind: Pod
metadata:
  name: mypod1
  labels:  # LABELS are what service SELECTORS use
    app: nginx

spec:
  containers:
    - name: mycontainer1
      image: docker-registry:5000/nginx
      ports:
        - containerPort: 80
