apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: pod1
  name: pod1
spec:
  containers:
  - image: docker-registry:5000/nginx
    name: pod1
    livenessProbe:
      exec:
        command: ["echo", "''"]
    readinessProbe:
      exec:
        command: ["curl", "service-am-i-ready:80"]
      initialDelaySeconds: 5
      periodSeconds: 5
  dnsPolicy: ClusterFirst
  restartPolicy: Always
