apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-pods-binding
  namespace: default

subjects:
- kind: ServiceAccount
  name: mikes-account
  ### apiGroup: rbac.authorization.k8s.io # ???
  namespace: default

roleRef:
  kind: Role
  name: read-pods # the role we defined earlier
  apiGroup: rbac.authorization.k8s.io
