apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: pod1
  name: pod1
spec:
  containers:
  - image: ubuntu
    name: pod1-container 
    command: ["sleep", "infinity"]
  dnsPolicy: ClusterFirst
  restartPolicy: Always
