apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
  namespace: mike-dev
spec:
  replicas: 2 
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
        - name: webapp
          image: nginx:latest
          ports:
          - containerPort: 80

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
  namespace: mike-prod
spec:
  replicas: 2 
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
        - name: webapp
          image: nginx:latest
          ports:
          - containerPort: 80

