apiVersion: v1
kind: Service
metadata:
  name: mikes-service
  namespace: mike-dev
spec:
  selector:
    app: webapp
  ports:
    - protocol: TCP
      targetPort: 80
      port: 80

---

apiVersion: v1
kind: Service
metadata:
  name: mikes-service
  namespace: mike-prod
spec:
  selector:
    app: webapp
  ports:
    - protocol: TCP
      targetPort: 80
      port: 80
