apiVersion: kubeadm.k8s.io/v1beta3 
kind: InitConfiguration
nodeRegistration:
  criSocket: "/var/run/containerd/containerd.sock"
---
apiVersion: kubeadm.k8s.io/v1beta3 
kind: ClusterConfiguration
networking:
  podSubnet: "10.244.0.0/16"  # Setting the pod network CIDR
kubernetesVersion: "stable"


