apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx-static
  name: nginx-static
spec:
  containers:
  - image: docker-registry:5000/nginx
    name: nginx-static
    resources:
      requests:
        memory: "20Mi"
        cpu: "10m" 
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
