apiVersion: apps/v1
kind: StatefulSet
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"StatefulSet","metadata":{"annotations":{},"name":"mike-stateful-set","namespace":"default"},"spec":{"minReadySeconds":2,"replicas":3,"selector":{"matchLabels":{"app":"mike-stateful-set"}},"serviceName":"nginx","template":{"metadata":{"labels":{"app":"mike-stateful-set"}},"spec":{"containers":[{"image":"docker-registry:5000/nginx","name":"nginx-stateful-pod"}],"terminationGracePeriodSeconds":10}}}}
  creationTimestamp: "2024-10-13T22:13:02Z"
  generation: 1
  name: mike-stateful-set
  namespace: default
  resourceVersion: "3157315"
  uid: dc1e09db-da92-41f3-b0cf-e8cbc89db831
spec:
  minReadySeconds: 2
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Retain
    whenScaled: Retain
  podManagementPolicy: OrderedReady
  replicas: 1 
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: mike-stateful-set
  serviceName: nginx
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mike-stateful-set
    spec:
      containers:
      - image: docker-registry:5000/nginx
        imagePullPolicy: Always
        name: nginx-stateful-pod
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 10
  updateStrategy:
    rollingUpdate:
      partition: 0
    type: RollingUpdate
status:
  availableReplicas: 3
  collisionCount: 0
  currentReplicas: 3
  currentRevision: mike-stateful-set-59f58d5d58
  observedGeneration: 1
  readyReplicas: 3
  replicas: 3
  updateRevision: mike-stateful-set-59f58d5d58
  updatedReplicas: 3
