apiVersion: v1
kind: PersistentVolume
metadata:
  name: mikes-pv
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 10Mi
  hostPath:
    path: /tmp/data  # where should we make this PV?
