apiVersion: v1
kind: Service
metadata:
  name: logserver-service
spec:
  type: NodePort  # For accessing externally, use NodePort or LoadBalancer in cloud setups
  ports:
  - port: 8081
    targetPort: 8081
    protocol: TCP
  selector:
    app: logserver
