apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  labels:
    app: myapp
    type: front-end
    mikekey: nginx # you can put anything in labels

spec:
  containers:
    - name: nginx-container
      image: docker-registry:5000/nginx
