apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: mikes-fedora 
spec:
  running: true
  template:
    metadata:
      labels:
        kubevirt.io/vm: mikes-fedora 
    spec:
      domain:
        cpu:
          cores: 1 
        memory:
          guest: 0.5Gi
        devices:
          disks:
          - name: disk0
            disk:
              bus: virtio
            bootOrder: 1
          interfaces:
          - name: default
            masquerade: {}
      networks:
      - name: default
        pod: {}
      volumes:
      - name: disk0
        persistentVolumeClaim:
          claimName: test-claim0 
