apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: hamster 
  name: processor 
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["configmaps", "secrets"]
  verbs: ["create"]
